name: atho
description: Athoapp cursos rápidos.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adobe_xd:
  flutter_svg: 
  chewie: 1.2.2
  video_player: 
  flutter_swiper: ^1.1.6
  # flutter_login_facebook: 1.0.1
  #firebase_core: "0.5.2+1"
  toast: ^0.1.5
  # flutter_signin_button: ^2.0.0
  http: any
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  provider: ^5.0.0
  dio: ^4.0.0
  intl: ^0.17.0 
  flutter_login: ^2.0.0
  font_awesome_flutter: ^9.0.0
  another_flushbar: ^1.10.23  
  percent_indicator: "^3.0.1"
  shared_preferences: ^2.0.6
  device_info_plus: "^2.2.0"
  # advance_pdf_viewer: ^2.0.0
  advance_pdf_viewer_fork: any
  universal_io: ^2.0.4
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  mobx_codegen: ^2.0.1
  test: ^1.0.0
  mockito: ^5.0.16
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/images/icon.png
    - assets/images/avatar_guy.png
    - assets/images/avatar_girl.png
    - assets/images/course1.png
    - assets/images/course2.png
    - assets/images/course3.png
    - assets/images/course4.jpg
    - assets/images/aproveitamento.jpg
    # - assets/images/logo-atho.png
    # - assets/images/playerbg.png
    - assets/images/knowledge.svg
    - assets/images/messaging.svg
    - assets/images/productive.svg
    - assets/images/media_player.svg
    - assets/images/logo.png
    - assets/images/ecorp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
          weight: 400
        - asset: fonts/PTSans-Bold.ttf
          weight: 700      
         
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
