// Mocks generated by Mockito 5.0.16 from annotations
// in atho/test/controllers/course_view_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:atho/models/curriculum.dart' as _i2;
import 'package:atho/models/lecture.dart' as _i3;
import 'package:atho/repositories/course_repository.dart' as _i5;
import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCurriculumModel_0 extends _i1.Fake implements _i2.CurriculumModel {}

class _FakeLectureModel_1 extends _i1.Fake implements _i3.LectureModel {}

class _FakeResponse_2<T> extends _i1.Fake implements _i4.Response<T> {}

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i5.CourseRepository {
  MockCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CurriculumModel> curriculum(int? subscribedCourseId,
          {Map<String, dynamic>? filter}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #curriculum, [subscribedCourseId], {#filter: filter}),
              returnValue:
                  Future<_i2.CurriculumModel>.value(_FakeCurriculumModel_0()))
          as _i6.Future<_i2.CurriculumModel>);
  @override
  _i6.Future<_i3.LectureModel> lecture(int? lectureId) => (super.noSuchMethod(
          Invocation.method(#lecture, [lectureId]),
          returnValue: Future<_i3.LectureModel>.value(_FakeLectureModel_1()))
      as _i6.Future<_i3.LectureModel>);
  @override
  _i6.Future<List<int>> completedLectures(int? course) => (super.noSuchMethod(
      Invocation.method(#completedLectures, [course]),
      returnValue: Future<List<int>>.value(<int>[])) as _i6.Future<List<int>>);
  @override
  _i6.Future<_i4.Response<dynamic>> deleteCompletedLectures(
          int? course, int? lecture) =>
      (super.noSuchMethod(
              Invocation.method(#deleteCompletedLectures, [course, lecture]),
              returnValue: Future<_i4.Response<dynamic>>.value(
                  _FakeResponse_2<dynamic>()))
          as _i6.Future<_i4.Response<dynamic>>);
  @override
  _i6.Future<_i4.Response<dynamic>> addCompletedLectures(
          int? course, int? lecture) =>
      (super.noSuchMethod(
              Invocation.method(#addCompletedLectures, [course, lecture]),
              returnValue: Future<_i4.Response<dynamic>>.value(
                  _FakeResponse_2<dynamic>()))
          as _i6.Future<_i4.Response<dynamic>>);
  @override
  String toString() => super.toString();
}
